services:
  db:
    image: mysql:5.7
    container_name: sqli_database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vulnerabile_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  api:
    build: .
    container_name: sqli_go_backend
    ports:
      - "9000:8080"
    volumes:
      - ./src:/app
    depends_on:
      - db